### ALL THE VARIABLES CAN BE OVERRITEN IN PROJECTS THAT USE THIS SHARED LIBRARY

variables:

### SONARQUBE VARIABLES
  SONAR_TOKEN: "your-sonarqube-token"
  SONAR_HOST_URL: "http://your-sonarqube-instance.org"
  SONAR_PROJECT_KEY: "your-project-key" # Unique identifier for the project
  SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
  SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
  # SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar" # Defines the location of the analysis task cache
  SONAR_SOURCES: "." # Comma-separated relative path from $CI_PROJECT_DIR containing main file. Default to .

  GIT_DEPTH: 0 # disable shallow clone

  ### SONARQUBE WITH DEPENDENCY CHEKCK VARIABLES
  SONAR_DCHECK_SKIP: "false"
  SONAR_DCHECK_SUMMARIZE: "false"

  # Specify a score of -1 to completely disable a severity
  SONAR_DCHECK_SEVERITY_BLOCKER: 9
  SONAR_DCHECK_SEVERITY_CRITICAL: 7
  SONAR_DCHECK_SEVERITY_MAJOR: 4
  SONAR_DCHECK_SEVERITY_MINOR: 0

  SONAR_DCHECK_SECURITY_HOTSPOT: "false"

# cache:
#   key: ${CI_JOB_NAME}
#   paths:
#     - .scannerwork

# STAGE DEFINITION
stages:
  - sonarqube

# SONARQUBE STAGE WITH DEPENDENCY CHECK PLUGIN
sonarqube:
  stage: sonarqube
  script:
    - docker run --rm -u $(id -u):$(id -g) -e SONAR_HOST_URL="$SONAR_HOST_URL" -e SONAR_LOGIN="$SONAR_TOKEN" -v "$CI_PROJECT_DIR:/usr/src" sonarsource/sonar-scanner-cli:latest sonar-scanner -Dsonar.exclusions=**\dependency-check-report\** -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.projectName="$SONAR_PROJECT_NAME" -Dsonar.sources="$SONAR_SOURCES" -Dsonar.sourceEncoding=UTF-8 -Dsonar.dependencyCheck.skip=$SONAR_DCHECK_SKIP -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report/dependency-check-report.html -Dsonar.dependencyCheck.severity.blocker=$SONAR_DCHECK_SEVERITY_BLOCKER -Dsonar.dependencyCheck.severity.critical=$SONAR_DCHECK_SEVERITY_CRITICAL -Dsonar.dependencyCheck.severity.major=$SONAR_DCHECK_SEVERITY_MAJOR -Dsonar.dependencyCheck.severity.minor=$SONAR_DCHECK_SEVERITY_MINOR -Dsonar.dependencyCheck.summarize=$SONAR_DCHECK_SUMMARIZE -Dsonar.dependencyCheck.securityHotspot=$SONAR_DCHECK_SECURITY_HOTSPOT

  allow_failure: true
  # only:
  #  - merge_requests
  #  - master
