### ALL THE VARIABLES CAN BE OVERRITEN IN PROJECTS THAT USE THIS SHARED LIBRARY

variables:

### SONARQUBE VARIABLES
  SONAR_TOKEN: "your-sonarqube-token"
  SONAR_HOST_URL: "http://your-sonarqube-instance.org"
  SONAR_PROJECT_KEY: "your-project-key" # Unique identifier for the project
  SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
  SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
  # SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar" # Defines the location of the analysis task cache
  SONAR_SOURCES: "." # Comma-separated relative path from $CI_PROJECT_DIR containing main file. Default to .

  GIT_DEPTH: 0 # disable shallow clone

# cache:
#   key: ${CI_JOB_NAME}
#   paths:
#     - .scannerwork

# STAGE DEFINITION
stages:
  - sonarqube

# SONARQUBE STAGE
sonarqube:
  stage: sonarqube
  script:
    - docker run --rm -u $(id -u):$(id -g) -e SONAR_HOST_URL="$SONAR_HOST_URL" -e SONAR_LOGIN="$SONAR_TOKEN" -v "$CI_PROJECT_DIR:/usr/src" sonarsource/sonar-scanner-cli:latest sonar-scanner -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.projectName="$SONAR_PROJECT_NAME" -Dsonar.sources="$SONAR_SOURCES" -Dsonar.sourceEncoding=UTF-8

  allow_failure: true
  # only:
  #  - merge_requests
  #  - master
