### ALL THE VARIABLES CAN BE OVERRITEN IN PROJECTS THAT USE THIS SHARED LIBRARY

variables:

### SSLYZE VARIABLES
  ### [IP address or domain]:[port]
  HOST: "mywebsite.com"

# STAGE DEFINITION
stages:
  - sslyze

# SSLYZE STAGE
sslyze:
  stage: sslyze
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/data artifactory.flx.thalesdigital.io/flxdp-docker/sslyze:1.0.0 "python3 -m sslyze --regular $HOST --json_out=/data/sslyze-report.json > /data/sslyze-report.txt"
  artifacts:
    paths:
      - sslyze-report.txt
      - sslyze-report.json
